version: '3'

services:
  mysql:
    build: ./docker/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_PASSWORD=fl11tw00d
      - MYSQL_DATABASE=banque_alimentaire
      - MYSQL_ROOT_PASSWORD=fl11tw00d
  #  volumes:
  #    - "./conf.d:/etc/mysql/conf.d:ro"

  keycloak:
    build: ./docker/keycloak
    ports:
      - "8083:8080"
    depends_on:
      - mysql
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2