FROM alpine as builder

ARG FRONTEND_URL
ARG REDIRECT_URIS
ARG MYSQL_HOST
ARG MYSQL_PORT
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_DATABASE
ARG SMTP_USER
ARG SMTP_PASSWORD

COPY ./build/realm/*.json /tmp/import/realm/
RUN sed -i 's@###REDIRECT_URIS###@'"$REDIRECT_URIS"'@' /tmp/import/realm/*.json && \
    sed -i 's@###FRONTEND_URL###@'"$FRONTEND_URL"'@' /tmp/import/realm/*.json && \
    sed -i 's@###SMTP_PASSWORD###@'"$SMTP_PASSWORD"'@' /tmp/import/realm/*.json && \
    sed -i 's@###SMTP_USER###@'"$SMTP_USER"'@' /tmp/import/realm/*.json


FROM jboss/keycloak:12.0.4
COPY ./build/datasource.xml /tmp/datasource.xml
# RUN sed -i 's@<drivers>@'"$(cat /tmp/datasource.xml)"'@' /opt/jboss/keycloak/standalone/configuration/standalone*.xml
RUN sed -e '/<drivers>/ {' -e 'r /tmp/datasource.xml' -e 'd' -e '}' -i /opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
COPY ./build/providers/*.jar /opt/jboss/keycloak/standalone/deployments/
COPY --from=builder /tmp/import/realm /tmp/import/realm/

